{
 "title": "InfluxDB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Test Case Status Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT status, \"name\"::tag FROM \"testresult\"\nWHERE $timeFilter\nORDER BY DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Test Status Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Passed",
     "query": "SELECT COUNT(\"status\") as \"Passed\" FROM \"testresult\"\nWHERE status='PASS' AND  $timeFilter"
    },
    {
     "alias": "Failed",
     "query": "SELECT COUNT(\"status\") as \"Failed\" FROM \"testresult\"\nWHERE status='FAIL' AND  $timeFilter"
    },
    {
     "alias": "Skipped",
     "query": "SELECT COUNT(\"status\") as \"Skipped\" FROM \"testresult\"\nWHERE status='SKIP' AND  $timeFilter"
    }
   ]
  },
  {
   "title": "Test Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Passed",
     "query": "SELECT COUNT(\"status\") as \"Passed\" FROM \"testresult\"\nWHERE status = 'PASS' AND $timeFilter\nGROUP BY time(1m)"
    },
    {
     "alias": "Failed",
     "query": "SELECT COUNT(\"status\") as \"Failed\" FROM \"testresult\"\nWHERE status = 'FAIL' AND $timeFilter\nGROUP BY time(1m)"
    },
    {
     "alias": "Skipped",
     "query": "SELECT COUNT(\"status\") as \"Skipped\" FROM \"testresult\"\nWHERE status = 'SKIP' AND $timeFilter\nGROUP BY time(1m)"
    }
   ]
  },
  {
   "title": "Test Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "keyword",
     "query": "SELECT \"name\"::tag, status, message FROM \"testresult\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}