{
 "title": "Postgres",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "SELECT metadata->>'version' from testrun_results"
   },
   {
    "name": "environment",
    "query": "SELECT metadata->>'environment' from testrun_results"
   },
   {
    "name": "run",
    "query": "SELECT metadata->>'test_run' from testrun_results"
   },
   { "name": "interval", "query": "1s,10s,1m,5m,15m,30m,60m,1d" },
   {
    "name": "project",
    "query": "SELECT metadata->>'project' from testrun_results"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Status",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT passed, failed, skipped FROM testrun_results WHERE metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'"
    }
   ]
  },
  {
   "title": "Tests per Suite",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT passed, failed, skipped, testsuite, endtime FROM testsuite_results WHERE metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'"
    }
   ]
  },
  {
   "title": "Test Duration",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT test, elapsedtime, status FROM test_results  WHERE metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run' ORDER BY elapsedtime DESC LIMIT 10"
    }
   ]
  },
  { "title": "Select Interval", "type": "volkovlabs-variable-panel", "gridPos": { "h": 20, "w": 3, "x": 0, "y": 13 } },
  {
   "title": "Tests per Time Intervall",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34') as \"time\",\r\n    COUNT(status) as \"Passed\"\r\nFROM\r\n    test_results\r\nWHERE status='PASS' AND metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'\r\nGROUP BY date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34')"
    },
    {
     "rawSql": "SELECT\r\n    date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34') as \"time\",\r\n    COUNT(status) as \"Failed\"\r\nFROM\r\n    test_results\r\nWHERE status='FAIL' AND metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'\r\nGROUP BY date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34')"
    }
   ]
  },
  {
   "title": "Tests per Time Intervall",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34') as \"time\",\r\n    COUNT(status) as \"Passed\"\r\nFROM\r\n    test_results\r\nWHERE status='PASS' AND metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'\r\nGROUP BY date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34')"
    },
    {
     "rawSql": "SELECT\r\n    date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34') as \"time\",\r\n    COUNT(status) as \"Failed\"\r\nFROM\r\n    test_results\r\nWHERE status='FAIL' AND metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'\r\nGROUP BY date_bin('$interval', \"endtime\",  TIMESTAMP '2023-08-29 10:34')"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH FailuresCount AS (\r\n  SELECT\r\n    test,\r\n    testsuite,\r\n    COUNT(*) FILTER (WHERE status = 'FAIL' AND endtime > endtime - INTERVAL '14 days') AS failures_in_last_14_days,\r\n    COUNT(*) FILTER (WHERE status = 'PASS' AND endtime > endtime - INTERVAL '14 days') AS passed_in_last_14_days\r\n  FROM\r\n    test_results\r\n\r\n  GROUP BY\r\n    test, testsuite\r\n)\r\nSELECT\r\n  tr.test,\r\n  tr.testsuite,\r\n  tr.status,\r\n  COALESCE(fc.failures_in_last_14_days, 0) AS \"Failures in last 14 days\",\r\n  COALESCE(fc.passed_in_last_14_days, 0) AS \"Passed in last 14 days\"\r\nFROM\r\n  test_results tr\r\nLEFT JOIN FailuresCount fc ON tr.test = fc.test AND tr.testsuite = fc.testsuite\r\nWHERE tr.status = 'FAIL' AND tr.metadata->>'version'='$version' AND tr.metadata->>'environment'='$environment' AND tr.metadata->>'project'='$project' AND tr.metadata->>'test_run'='$run'\r\nGROUP BY\r\n  tr.test, tr.testsuite, tr.status, \"Failures in last 14 days\", \"Passed in last 14 days\"\r\nORDER BY\r\n  tr.test, tr.testsuite;\r\n"
    }
   ]
  },
  {
   "title": "Elapsed per Suite",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT elapsedtime, testsuite FROM testsuite_results WHERE metadata->>'version'='$version' AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'"
    }
   ]
  },
  {
   "title": "Test Runs over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT starttime as \"time\", passed as \"Passed\", failed as \"Failed\", skipped as \"Skipped\" FROM testrun_results WHERE metadata->>'project'='$project'"
    }
   ]
  },
  {
   "title": "Test Timeline",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    starttime,\r\n    endtime  as \"time\",\r\n    test,\r\n    status\r\nFROM\r\n    test_results\r\nWHERE $__timeFilter(starttime) AND metadata->>'environment'='$environment' AND metadata->>'project'='$project' AND metadata->>'test_run'='$run'"
    }
   ]
  }
 ]
}